### ISSUE TITLE
"Add to Slack" Installation link on website not working

### ISSUE THREAD

**Issue by Cardridge** [a-rmz/sbotify#3]
After clicking "Authorize" it just says `Tunnel c557f018.ngrok.io not found`.

**Comment by a-rmz** [comment]
Thanks for the heads up! I was doing some testing and it was pointing to my development stage. I'll fix this asap. :)

**Comment by a-rmz** [comment]
Done, you can install it. 😄

**Comment by Cardridge** [comment]
Thank you!
